### ISSUE TITLE
您好,您的docker已经跑通了,并且安装了vim,但是一执行您的脚本,再回来看,修改的代码和内容全部消失了,如何保存您docker的修改呢?

### ISSUE THREAD

**Issue by TheSeanParker** [Lavinci/aloam-docker#1]

**Comment by Lavinci** [comment]
你好，你可以通过docker cp filename 来保存容器中的内容
或者自行修改Dockerfile来重新构建你的容器

**Comment by TheSeanParker** [comment]
> 你好，你可以通过docker cp filename 来保存容器中的内容 或者自行修改Dockerfile来重新构建你的容器

好的,谢谢您
